Fixed NoSuchMethodError when livy-repl starts up.
Downgrade json4s from 3.2.11 to 3.2.10. json4s 3.2.11 removed a required API without bumping minor version.